FROM node:18-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# # Build the application
# RUN npm run build

# Production image
FROM node:18-alpine AS runner

WORKDIR /src/app/(frontend)

# Expose port 3000
EXPOSE 3000

# Start the server
CMD ["npm", "start"]
