/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    pages: Page
    projects: Project
    blogs: Blog
    'contact-forms': ContactForm
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    pages: PagesSelect<false> | PagesSelect<true>
    projects: ProjectsSelect<false> | ProjectsSelect<true>
    blogs: BlogsSelect<false> | BlogsSelect<true>
    'contact-forms': ContactFormsSelect<false> | ContactFormsSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences':
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>
    'payload-migrations':
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  globals: {
    'site-settings': SiteSetting
  }
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>
  }
  locale: null
  user: User & {
    collection: 'users'
  }
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  password?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  alt: string
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number
  title: string
  pageLayout?:
    | (
        | {
            /**
             * The greeting text displayed on the home page.
             */
            greetText?: string | null
            /**
             * The name to be displayed prominently on the home page.
             */
            name: string
            /**
             * A short description or tagline to describe yourself or your site.
             */
            description?: {
              root: {
                type: string
                children: {
                  type: string
                  version: number
                  [k: string]: unknown
                }[]
                direction: ('ltr' | 'rtl') | null
                format:
                  | 'left'
                  | 'start'
                  | 'center'
                  | 'right'
                  | 'end'
                  | 'justify'
                  | ''
                indent: number
                version: number
              }
              [k: string]: unknown
            } | null
            /**
             * A profile picture to display on the home page.
             */
            profileImage?: (number | null) | Media
            /**
             * A list of social media links to display on the home page.
             */
            socialLinks?:
              | {
                  /**
                   * The social media platform for this link.
                   */
                  platform:
                    | 'github'
                    | 'linkedin'
                    | 'twitter'
                    | 'instagram'
                    | 'facebook'
                    | 'youtube'
                  /**
                   * The URL to your profile on this platform.
                   */
                  url: string
                  id?: string | null
                }[]
              | null
            /**
             * The text for the main call-to-action button on the home page.
             */
            button?: string | null
            /**
             * The URL or path the button navigates to.
             */
            buttonPath?: string | null
            id?: string | null
            blockName?: string | null
            blockType: 'homeBlock'
          }
        | {
            /**
             * The main heading for the tech stacks section.
             */
            heading: string
            /**
             * A subheading or brief description for the tech stacks section.
             */
            subheading?: string | null
            /**
             * Categories of technologies you are proficient in.
             */
            techStacks?:
              | {
                  /**
                   * The category name (e.g., "Frontend", "Backend", "DevOps").
                   */
                  category: string
                  /**
                   * List of technologies in this category.
                   */
                  technologies?:
                    | {
                        /**
                         * The name of the technology.
                         */
                        name: string
                        /**
                         * An icon representing this technology.
                         */
                        icon?: (number | null) | Media
                        id?: string | null
                      }[]
                    | null
                  id?: string | null
                }[]
              | null
            id?: string | null
            blockName?: string | null
            blockType: 'stacksBlock'
          }
        | {
            /**
             * The main heading for the about section.
             */
            heading: string
            /**
             * A subheading or brief description for the about section.
             */
            subheading?: string | null
            /**
             * Your profile image to display in the about section.
             */
            profileImage?: (number | null) | Media
            /**
             * A detailed description about yourself, your background, and your interests.
             */
            aboutYourself?: {
              root: {
                type: string
                children: {
                  type: string
                  version: number
                  [k: string]: unknown
                }[]
                direction: ('ltr' | 'rtl') | null
                format:
                  | 'left'
                  | 'start'
                  | 'center'
                  | 'right'
                  | 'end'
                  | 'justify'
                  | ''
                indent: number
                version: number
              }
              [k: string]: unknown
            } | null
            /**
             * Additional details about yourself organized by categories.
             */
            details?:
              | {
                  /**
                   * The title or category of these details.
                   */
                  detailsTitle: string
                  /**
                   * Points or items under this detail category.
                   */
                  detailPoints?:
                    | {
                        /**
                         * A specific point or item of information.
                         */
                        detailPoint: string
                        id?: string | null
                      }[]
                    | null
                  id?: string | null
                }[]
              | null
            /**
             * Text to display on the button.
             */
            buttonText?: string | null
            /**
             * URL or path the button should link to.
             */
            buttonPath?: string | null
            /**
             * Your coding profiles on various platforms.
             */
            codeProfiles?: {
              /**
               * Heading for the code profiles section.
               */
              heading?: string | null
              /**
               * List of your coding profiles.
               */
              profiles?:
                | {
                    /**
                     * Name of the coding platform.
                     */
                    title: string
                    /**
                     * URL to your profile on this platform.
                     */
                    url: string
                    /**
                     * Logo or image for this coding platform.
                     */
                    image?: (number | null) | Media
                    id?: string | null
                  }[]
                | null
            }
            id?: string | null
            blockName?: string | null
            blockType: 'aboutBlock'
          }
        | {
            /**
             * The main heading for the experiences section.
             */
            heading: string
            /**
             * A subheading or brief description for the experiences section.
             */
            subheading?: string | null
            /**
             * Add your work experiences here.
             */
            experiences?:
              | {
                  /**
                   * Your job title or position.
                   */
                  title: string
                  /**
                   * The name of the company you worked for.
                   */
                  company: string
                  /**
                   * URL to the company website.
                   */
                  companyLink?: string | null
                  /**
                   * Logo of the company you worked for.
                   */
                  companyLogo?: (number | null) | Media
                  /**
                   * The location where you worked.
                   */
                  location?: string | null
                  /**
                   * When you started working at this position.
                   */
                  startDate?: string | null
                  /**
                   * When you finished working at this position.
                   */
                  endDate?: string | null
                  /**
                   * Check if this is your current job.
                   */
                  current?: boolean | null
                  /**
                   * Details about your work and responsibilities.
                   */
                  workDetails?:
                    | {
                        /**
                         * Description of your work responsibilities or projects.
                         */
                        description?: {
                          root: {
                            type: string
                            children: {
                              type: string
                              version: number
                              [k: string]: unknown
                            }[]
                            direction: ('ltr' | 'rtl') | null
                            format:
                              | 'left'
                              | 'start'
                              | 'center'
                              | 'right'
                              | 'end'
                              | 'justify'
                              | ''
                            indent: number
                            version: number
                          }
                          [k: string]: unknown
                        } | null
                        id?: string | null
                      }[]
                    | null
                  /**
                   * Skills you utilized in this position.
                   */
                  skills?:
                    | {
                        /**
                         * A skill you used in this role.
                         */
                        skill: string
                        id?: string | null
                      }[]
                    | null
                  /**
                   * Heading for the achievements section.
                   */
                  achievementsHeading?: string | null
                  /**
                   * Your key achievements in this role.
                   */
                  achievements?:
                    | {
                        /**
                         * Description of your achievement.
                         */
                        description?: string | null
                        id?: string | null
                      }[]
                    | null
                  id?: string | null
                }[]
              | null
            id?: string | null
            blockName?: string | null
            blockType: 'experiencesBlock'
          }
        | {
            /**
             * The main heading for the contact section.
             */
            heading: string
            /**
             * A description or brief text for the contact section.
             */
            subheading?: string | null
            /**
             * Your contact email address.
             */
            email?: string | null
            /**
             * Your contact phone number.
             */
            phone?: string | null
            /**
             * List of reasons why someone might contact you.
             */
            contactReasons?:
              | {
                  /**
                   * A reason or category for contact (e.g., "Business Inquiry", "Job Opportunity").
                   */
                  reason: string
                  /**
                   * A brief description of this contact reason.
                   */
                  description?: string | null
                  id?: string | null
                }[]
              | null
            /**
             * Text to display on the contact form submit button.
             */
            submitButtonText?: string | null
            id?: string | null
            blockName?: string | null
            blockType: 'contactBlock'
          }
        | {
            /**
             * The main heading for the form section.
             */
            heading: string
            /**
             * Define the fields that will appear in your form.
             */
            formFields?:
              | {
                  /**
                   * The label for this form field.
                   */
                  label: string
                  /**
                   * The type of input field to display.
                   */
                  type:
                    | 'text'
                    | 'email'
                    | 'textarea'
                    | 'select'
                    | 'checkbox'
                    | 'radio'
                  /**
                   * Check if this field is required to be filled out.
                   */
                  required?: boolean | null
                  id?: string | null
                }[]
              | null
            /**
             * Text to display on the form submit button.
             */
            submitButtonText?: string | null
            id?: string | null
            blockName?: string | null
            blockType: 'formBlock'
          }
        | {
            /**
             * Your Disqus shortname from your Disqus account.
             */
            disqusShortname: string
            /**
             * A unique identifier for the comment thread (optional).
             */
            identifier?: string | null
            id?: string | null
            blockName?: string | null
            blockType: 'disqusCommentBlock'
          }
        | {
            /**
             * The title for this list section.
             */
            heading: string
            /**
             * Select which collection to display items from.
             */
            collectionSlug: 'blogs' | 'projects'
            id?: string | null
            blockName?: string | null
            blockType: 'listBlock'
          }
        | {
            /**
             * Select which collection to display content from.
             */
            collectionSlug: 'blogs' | 'projects'
            id?: string | null
            blockName?: string | null
            blockType: 'dynamicContentBlock'
          }
      )[]
    | null
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media
    keywords?: string | null
  }
  slugMode?: ('generate' | 'custom') | null
  slug?: string | null
  pathMode?: ('generate' | 'custom') | null
  path?: string | null
  parent?: (number | null) | Page
  breadcrumbs?:
    | {
        label: string
        url: string
        id?: string | null
      }[]
    | null
  pageSettings?: {
    isHomePage?: boolean | null
    isDynamicPage?: boolean | null
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number
  projectType: 'major' | 'minor'
  projectName: string
  projectImage: number | Media
  summary: string
  projectLinks?:
    | {
        serviceName: string
        serviceLink: string
        id?: string | null
      }[]
    | null
  features?:
    | {
        feature: string
        id?: string | null
      }[]
    | null
  techStack?:
    | {
        technology: string
        technologyIcon?: (number | null) | Media
        id?: string | null
      }[]
    | null
  /**
   * Auto-generated from Project Name
   */
  slug?: string | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number
  title: string
  /**
   * Select the platform where the blog is published
   */
  platform: 'medium' | 'devto' | 'hashnode' | 'other'
  /**
   * This image will be displayed as the blog preview
   */
  featuredImage: number | Media
  /**
   * A brief description of what the blog is about
   */
  summary: string
  /**
   * The full URL to your blog post
   */
  externalLink: string
  /**
   * When was this blog published?
   */
  publishedDate: string
  /**
   * Add up to 5 tags to categorize your blog
   */
  tags?:
    | {
        tag: string
        id?: string | null
      }[]
    | null
  /**
   * Auto-generated from Blog Title
   */
  slug?: string | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-forms".
 */
export interface ContactForm {
  id: number
  /**
   * Name of the person submitting the form
   */
  name: string
  /**
   * Email address of the sender
   */
  email: string
  /**
   * Phone number (optional)
   */
  phone?: string | null
  /**
   * Subject of the message
   */
  subject: string
  /**
   * Content of the message
   */
  message: string
  /**
   * Current status of this contact form submission
   */
  status?: ('UNREAD' | 'READ' | 'IN_PROGRESS' | 'COMPLETED' | 'ARCHIVED') | null
  /**
   * Priority level of this contact request
   */
  priority?: ('high' | 'normal' | 'low') | null
  /**
   * Internal notes about this contact (only visible to admin)
   */
  internalNotes?: string | null
  /**
   * Source of the contact form submission
   */
  source?: ('website' | 'api' | 'other') | null
  /**
   * IP address of the sender
   */
  ipAddress?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
    | ({
        relationTo: 'pages'
        value: number | Page
      } | null)
    | ({
        relationTo: 'projects'
        value: number | Project
      } | null)
    | ({
        relationTo: 'blogs'
        value: number | Blog
      } | null)
    | ({
        relationTo: 'contact-forms'
        value: number | ContactForm
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  _status?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T
  pageLayout?:
    | T
    | {
        homeBlock?:
          | T
          | {
              greetText?: T
              name?: T
              description?: T
              profileImage?: T
              socialLinks?:
                | T
                | {
                    platform?: T
                    url?: T
                    id?: T
                  }
              button?: T
              buttonPath?: T
              id?: T
              blockName?: T
            }
        stacksBlock?:
          | T
          | {
              heading?: T
              subheading?: T
              techStacks?:
                | T
                | {
                    category?: T
                    technologies?:
                      | T
                      | {
                          name?: T
                          icon?: T
                          id?: T
                        }
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        aboutBlock?:
          | T
          | {
              heading?: T
              subheading?: T
              profileImage?: T
              aboutYourself?: T
              details?:
                | T
                | {
                    detailsTitle?: T
                    detailPoints?:
                      | T
                      | {
                          detailPoint?: T
                          id?: T
                        }
                    id?: T
                  }
              buttonText?: T
              buttonPath?: T
              codeProfiles?:
                | T
                | {
                    heading?: T
                    profiles?:
                      | T
                      | {
                          title?: T
                          url?: T
                          image?: T
                          id?: T
                        }
                  }
              id?: T
              blockName?: T
            }
        experiencesBlock?:
          | T
          | {
              heading?: T
              subheading?: T
              experiences?:
                | T
                | {
                    title?: T
                    company?: T
                    companyLink?: T
                    companyLogo?: T
                    location?: T
                    startDate?: T
                    endDate?: T
                    current?: T
                    workDetails?:
                      | T
                      | {
                          description?: T
                          id?: T
                        }
                    skills?:
                      | T
                      | {
                          skill?: T
                          id?: T
                        }
                    achievementsHeading?: T
                    achievements?:
                      | T
                      | {
                          description?: T
                          id?: T
                        }
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        contactBlock?:
          | T
          | {
              heading?: T
              subheading?: T
              email?: T
              phone?: T
              contactReasons?:
                | T
                | {
                    reason?: T
                    description?: T
                    id?: T
                  }
              submitButtonText?: T
              id?: T
              blockName?: T
            }
        formBlock?:
          | T
          | {
              heading?: T
              formFields?:
                | T
                | {
                    label?: T
                    type?: T
                    required?: T
                    id?: T
                  }
              submitButtonText?: T
              id?: T
              blockName?: T
            }
        disqusCommentBlock?:
          | T
          | {
              disqusShortname?: T
              identifier?: T
              id?: T
              blockName?: T
            }
        listBlock?:
          | T
          | {
              heading?: T
              collectionSlug?: T
              id?: T
              blockName?: T
            }
        dynamicContentBlock?:
          | T
          | {
              collectionSlug?: T
              id?: T
              blockName?: T
            }
      }
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
        keywords?: T
      }
  slugMode?: T
  slug?: T
  pathMode?: T
  path?: T
  parent?: T
  breadcrumbs?:
    | T
    | {
        label?: T
        url?: T
        id?: T
      }
  pageSettings?:
    | T
    | {
        isHomePage?: T
        isDynamicPage?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  projectType?: T
  projectName?: T
  projectImage?: T
  summary?: T
  projectLinks?:
    | T
    | {
        serviceName?: T
        serviceLink?: T
        id?: T
      }
  features?:
    | T
    | {
        feature?: T
        id?: T
      }
  techStack?:
    | T
    | {
        technology?: T
        technologyIcon?: T
        id?: T
      }
  slug?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T
  platform?: T
  featuredImage?: T
  summary?: T
  externalLink?: T
  publishedDate?: T
  tags?:
    | T
    | {
        tag?: T
        id?: T
      }
  slug?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-forms_select".
 */
export interface ContactFormsSelect<T extends boolean = true> {
  name?: T
  email?: T
  phone?: T
  subject?: T
  message?: T
  status?: T
  priority?: T
  internalNotes?: T
  source?: T
  ipAddress?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number
  title: string
  description?: string | null
  /**
   * We recommend a maximum size of 256 * 256 pixels
   */
  favicon?: (number | null) | Media
  /**
   * We recommend a maximum size of 1200 * 630 pixels
   */
  ogImage?: (number | null) | Media
  /**
   * Separate keywords with commas
   */
  keywords?: string | null
  logo: {
    image: number | Media
    height?: number | null
    width?: number | null
  }
  menuLinks?:
    | {
        group?: boolean | null
        link: {
          type?: ('internal' | 'custom') | null
          openInNewTab?: boolean | null
          /**
           * Upload an svg or logo to be displayed with link
           */
          icon?: (number | null) | Media
          label: string
          page?: (number | null) | Page
          url?: string | null
        }
        id?: string | null
      }[]
    | null
  footerLogo?: {
    image?: (number | null) | Media
    height?: number | null
    width?: number | null
  }
  footerText?: string | null
  footerLinks?:
    | {
        group?: string | null
        links?:
          | {
              label: string
              url: string
              id?: string | null
            }[]
          | null
        id?: string | null
      }[]
    | null
  socialLinks?:
    | {
        platform: string
        icon?: (number | null) | Media
        url: string
        id?: string | null
      }[]
    | null
  redirects?:
    | {
        /**
         * The path to redirect from (e.g., /old-page)
         */
        fromPath: string
        /**
         * The path to redirect to (e.g., /new-page)
         */
        toPath: string
        isPermanent?: boolean | null
        isEnabled?: boolean | null
        id?: string | null
      }[]
    | null
  ads?: {
    enabled?: boolean | null
    adsenseId?: string | null
    placements?:
      | {
          type: 'header' | 'sidebar' | 'content' | 'footer'
          code?: string | null
          id?: string | null
        }[]
      | null
  }
  affiliate?: {
    enabled?: boolean | null
    disclosure?: string | null
  }
  _status?: ('draft' | 'published') | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  title?: T
  description?: T
  favicon?: T
  ogImage?: T
  keywords?: T
  logo?:
    | T
    | {
        image?: T
        height?: T
        width?: T
      }
  menuLinks?:
    | T
    | {
        group?: T
        link?:
          | T
          | {
              type?: T
              openInNewTab?: T
              icon?: T
              label?: T
              page?: T
              url?: T
            }
        id?: T
      }
  footerLogo?:
    | T
    | {
        image?: T
        height?: T
        width?: T
      }
  footerText?: T
  footerLinks?:
    | T
    | {
        group?: T
        links?:
          | T
          | {
              label?: T
              url?: T
              id?: T
            }
        id?: T
      }
  socialLinks?:
    | T
    | {
        platform?: T
        icon?: T
        url?: T
        id?: T
      }
  redirects?:
    | T
    | {
        fromPath?: T
        toPath?: T
        isPermanent?: T
        isEnabled?: T
        id?: T
      }
  ads?:
    | T
    | {
        enabled?: T
        adsenseId?: T
        placements?:
          | T
          | {
              type?: T
              code?: T
              id?: T
            }
      }
  affiliate?:
    | T
    | {
        enabled?: T
        disclosure?: T
      }
  _status?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
